feat: stats service
SidyakinV/java-explore-with-me pull request #1
Opened 2024-06-25 05:42 UTC by SidyakinV

2024-06-25 09:43 UTC, TomattmanYandex requested changes
Нужны минимальные правки

2024-06-25 09:43 UTC, TomattmanYandex commented on stat-service/src/main/java/ru/practicum/ewm/storage/StatsStorage.java
> +public class StatsStorage {
Зачем тебе сразу StatsRepository и StatsStorage
Ведь они делают одно и то же, делают запросы в базу данных
но StatsRepository это стандартный спринговый подход а StatsStorage это то как это делают не использований всех преимуществ
 стоит удалить этот класс

2024-06-25 15:48 UTC, SidyakinV commented on stat-service/src/main/java/ru/practicum/ewm/storage/StatsStorage.java
> +public class StatsStorage {
Здесь опять та же самая извечная проблема - нас ничему не учат, а отсылают за знаниями в инет.
А там я вижу, что интерфейс JpaRepository хорош ровно до тех пор, пока не нужно реализовать какой-то сложный запрос, как, допустим, сейчас у нас, с подзапросами и вариативными критериями отбора.
В результате вместо одного метода с динамически формируемым запросом мне пришлось сделать 4 запроса под два условия. А если завтра этих условий станет 10? Это ж сколько однотипных запросов я должен буду написать? А если к тому же потом поменяется логика запроса, ее же нужно будет подправить во всех (!) методах.
Изначально ведь я так и сделал, но понял, что это категорически неправильный подход, и переделал с использованием дополнительного класса.
И еще один момент. Вся эта подкапотная гибернация хороша до тех пор, пока используются простые запросы. А ведь в жизни бывают сложные запросы, требующие оптимизации. И здесь только ручками, только ручками.
Поэтому я и избрал такой подход - использовать два разных класса под два разных типа задач, пусть и работающих с одними и теми же данными.

2024-06-26 09:34 UTC, TomattmanYandex approved these changes
Принято

2024-06-26 09:58 UTC, merged